Fangorn refactor
gaia-os/fangorn pull request #13
Opened 2023-03-27 16:23 UTC by dimarkov

Previously the package was not setup correctly for installation with 
```bash
pip install -e .
```
This will be relevant to make correctly for future publication of the package on pypi so that it can be installed as 
```bash
pip install digital_gaia
```

Following the previous structure the top level package name is digital_gaia, and fangorn and utils are first level 
subpackages. utils package contains what was previous in scripts folder, except the run_like_in_notebook.py. 
run_like_in_notebook.py is now inside the scripts folder that sits outside of the source code (src folder) containing all the packages. I have also changed all .py files to lower case names, as there is a clash between a python file and the class name which is within the file.

2023-03-27 16:27 UTC, dimarkov commented
One can now run the files inside the scripts folder as follows 
```bash
python -m scripts.run_like_in_notebook
```

2023-03-31 00:11 UTC, ChampiB requested changes
Great job on this one! It seems like there are a lot of comments but it is mostly small style things, and renaming of files. I have not checked that it runs yet, but as soon as you are done applying these feedback, I will do a final (functional) check!

2023-03-31 00:11 UTC, ChampiB commented on src/digital_gaia/fangorn/ontology/v1/environment/base/meteorology/Weather.py
For concistency, we may want rename this file name using lower case and underscore (when applicable)

2023-03-31 00:11 UTC, ChampiB commented on src/digital_gaia/fangorn/ontology/v1/management/base/agriculture/AlfalfaCompost.py
For concistency, we may want rename this file name using lower case and underscore (when applicable)

2023-03-31 00:11 UTC, ChampiB commented on src/digital_gaia/fangorn/ontology/v1/management/base/agriculture/CowManure.py
For concistency, we may want rename this file name using lower case and underscore (when applicable)

2023-03-31 00:11 UTC, ChampiB commented on src/digital_gaia/fangorn/ontology/v1/management/base/agriculture/Harvest.py
For concistency, we may want rename this file name using lower case and underscore (when applicable)

2023-03-31 00:11 UTC, ChampiB commented on src/digital_gaia/fangorn/ontology/v1/management/base/agriculture/Herbicide.py
For concistency, we may want rename this file name using lower case and underscore (when applicable)

2023-03-31 00:11 UTC, ChampiB commented on src/digital_gaia/fangorn/ontology/v1/management/base/agriculture/Irrigation.py
For concistency, we may want rename this file name using lower case and underscore (when applicable)

2023-03-31 00:11 UTC, ChampiB commented on src/digital_gaia/fangorn/ontology/v1/management/base/agriculture/Mycorrhizae.py
For concistency, we may want rename this file name using lower case and underscore (when applicable)

2023-03-31 00:11 UTC, ChampiB commented on src/digital_gaia/fangorn/ontology/v1/management/base/agriculture/Pesticide.py
For concistency, we may want rename this file name using lower case and underscore (when applicable)

2023-03-31 00:11 UTC, ChampiB commented on src/digital_gaia/fangorn/ontology/v1/management/base/agriculture/Planting.py
For concistency, we may want rename this file name using lower case and underscore (when applicable)

2023-03-31 00:11 UTC, ChampiB commented on src/digital_gaia/fangorn/ontology/v1/management/base/agriculture/Pruning.py
For concistency, we may want rename this file name using lower case and underscore (when applicable)

2023-03-31 00:11 UTC, ChampiB commented on src/digital_gaia/fangorn/ontology/v1/management/base/agriculture/Rhizobacteria.py
For concistency, we may want rename this file name using lower case and underscore (when applicable)

2023-03-31 00:11 UTC, ChampiB commented on src/digital_gaia/fangorn/ontology/v1/management/base/agriculture/Tillage.py
For concistency, we may want rename this file name using lower case and underscore (when applicable)

2023-03-31 00:11 UTC, ChampiB commented on src/digital_gaia/fangorn/ontology/v1/management/base/agriculture/VermiCompost.py
For concistency, we may want rename this file name using lower case and underscore (when applicable)

2023-03-31 00:11 UTC, ChampiB commented on src/digital_gaia/fangorn/ontology/v1/measurement/base/agriculture/PlantDensity.py
For concistency, we may want rename this file name using lower case and underscore (when applicable)

2023-03-31 00:11 UTC, ChampiB commented on src/digital_gaia/fangorn/ontology/v1/measurement/base/agriculture/PlantHeight.py
For concistency, we may want rename this file name using lower case and underscore (when applicable)

2023-03-31 00:11 UTC, ChampiB commented on src/digital_gaia/fangorn/ontology/v1/measurement/base/agriculture/Yield.py
For concistency, we may want rename this file name using lower case and underscore (when applicable)

2023-03-31 00:11 UTC, ChampiB commented on src/digital_gaia/fangorn/ontology/v1/society/base/agriculture/Labor.py
For concistency, we may want rename this file name using lower case and underscore (when applicable)

2023-04-03 10:47 UTC, dimarkov commented on setup.py
> +	'meteostat',
I do not see it, it is aligned for me.

2023-04-20 14:46 UTC, dimarkov commented on scripts/generate_reports.py
This is wrong
src.digital_gaia 
is not a path for the package. 
Frist src folder does not exist once you install the package, second you want to work with relative import only because if you decide to change the structure, e.g. name of the root folder you brake the entire dependency and have to change paths in all downstream files.

2023-05-06 19:00 UTC, ChampiB approved these changes

2023-05-06 19:04 UTC, ChampiB approved these changes

2023-05-07 07:37 UTC, merged