TODO: add title
gaia-os/fangorn pull request #14
Opened 2023-03-30 13:23 UTC by nanidelca

TODO: add description of changes

2023-04-04 17:24 UTC, ChampiB requested changes
Very good pull request overall, just a few minor style things that would be good to correct, most of them related to the PEP8 norm. Great job!

2023-04-04 17:24 UTC, ChampiB commented on digital_gaia/fangorn/agents/impl/roots_agent.py
> +        return deterministic("labor_monetary_cost", ((a + b + c + d + e) * params["labor_cost"]) + labor_monetary_cost_t)
Another PEP8 rule is to keep the line length under 120 characters, this line is too long, and if you perform the changes requested above it will become even longer.

I would recommend the creation of a new variable as follows:
```
        total_hours = a + b + c + d + e
        return deterministic("labor_monetary_cost", total_hours * params["labor_cost"] + labor_monetary_cost_t)
```

2023-04-04 17:24 UTC, ChampiB commented on digital_gaia/fangorn/agents/impl/roots_agent.py
> +        :param day_hours_18: 18 hours of dayligth
Just a small typo here, dayligth should be daylight

2023-04-04 17:24 UTC, ChampiB commented on digital_gaia/fangorn/agents/impl/roots_agent.py
> +
Naming the variables "a", "b", ..., "f" is not a good practice. More on that below.

Also, the above line contains useless parentheses, e.g.,
`a = (sprouting_tent * day_hours_24 * 24 * params["tent_day_energy_use"])`
could be written:
`a = sprouting_tent * day_hours_24 * 24 * params["tent_day_energy_use"]`

2023-04-04 17:24 UTC, ChampiB commented on digital_gaia/fangorn/agents/impl/roots_agent.py
> +
This can be simplified but the engine does not provide the right functionality yet. Please add the following todo:
`# TODO: allow parameter values to be passed from the project configuration, i.e., NumberDayHours=12`

2023-04-10 12:52 UTC, nanidelca commented on digital_gaia/fangorn/ontology/v1/management/base/agriculture/DayHours.py
@mattjenkins3 any comments here?

2023-04-10 14:12 UTC, nanidelca commented on data/projects/Roots-and-Culture/roots-indoor1.json
> +
Done

2023-04-10 14:16 UTC, nanidelca commented on digital_gaia/fangorn/agents/impl/roots_agent.py
> +            "time_delta": 1,  # units: week, TODO change that to make it realistic, it is equal to 1 week and to compute plant size
Done

2023-04-10 14:26 UTC, nanidelca commented on digital_gaia/fangorn/agents/impl/roots_agent.py
>          }
Done

2023-04-10 14:31 UTC, nanidelca commented on digital_gaia/fangorn/agents/impl/roots_agent.py
> +            #Computed the expected energy monetary cost at time t + 1
Done

2023-04-12 12:15 UTC, nanidelca commented on digital_gaia/fangorn/agents/impl/roots_agent.py
> +            #Computed the expected labor monetary cost at time t + 1
Done

2023-04-12 12:15 UTC, nanidelca commented on digital_gaia/fangorn/agents/impl/roots_agent.py
> +            #Computed the expexted total monetary cost at time t + 1
Done!

2023-04-12 12:19 UTC, nanidelca commented on digital_gaia/fangorn/agents/impl/roots_agent.py
>          # Create the states at time t + 1
Done

2023-04-12 12:47 UTC, nanidelca commented on digital_gaia/fangorn/agents/impl/roots_agent.py
> +    def compute_total_cost(labor_monetary_cost, energy_monetary_cost):
Done!

2023-04-12 13:04 UTC, nanidelca commented on digital_gaia/fangorn/agents/impl/roots_agent.py
> +        e = irrigate * params["labor_use_irrigation"]
Great, done!

2023-04-12 13:04 UTC, nanidelca commented on digital_gaia/fangorn/agents/impl/roots_agent.py
> +        return deterministic("labor_monetary_cost", ((a + b + c + d + e) * params["labor_cost"]) + labor_monetary_cost_t)
Done!

2023-04-12 14:44 UTC, nanidelca commented on digital_gaia/fangorn/agents/impl/roots_agent.py
> +
I removed the useless parentheses and changed variable names. I also created a new variable "total energy use", and followed PEP8 convention to break a long line there.

2023-05-07 08:57 UTC, ChampiB approved these changes

2023-05-09 07:12 UTC, ChampiB approved these changes

2023-05-09 07:12 UTC, merged